name: Rust

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install nasm
      run: |
        wget https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/nasm-2.14.02.tar.gz
        tar -xvf nasm-2.14.02.tar.gz
        cd nasm-2.14.02
        ./autogen.sh
        ./configure --prefix=/usr
        make
        sudo make install
        nasm -v
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
